FROM python:3.10-slim

WORKDIR /app

COPY serverB/requirements.strategy.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

CMD ["python", "serverB/strategy_service.py"]
