FROM node:18-bullseye-slim AS build

WORKDIR /app

# Copy frontend sources
COPY serverB/frontend/package.json ./
COPY serverB/frontend/ ./

	RUN npm install --legacy-peer-deps \
		&& npm install ajv@^8 ajv-keywords@^5
	RUN npm run build

FROM node:18-bullseye-slim AS runner
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/build /app/build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
