FROM python:3.10-slim

WORKDIR /app

# install build deps
COPY serverB/requirements.execution.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY . /app

CMD ["python", "serverB/run_execution.py"]
